version: 2

jobs:
  build:
    docker:
      - image: headspace/hs-node:7.10 # primary container
        environment:
          NODE_ENV: test
    working_directory: /test
    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            yarn

      - run:
          name: Run tests
          command: |
            yarn test

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "~/.yarn-cache"

      - store_artifacts:
          path: coverage/

      - store_test_results:
          path: test-output/

      - deploy:
          name: Maybe publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn run semantic-release-beta
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run semantic-release
            fi

      - deploy:
          name: Maybe build for deployment
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              echo "do tag deploy stuff here"
            fi

deployment:
  production:
    tag: /v[0-9]+(\.[0-9]+)*/
